mv multiplierHolder.js.txt     multiplierHolder.js      
mv multiplierHolder_stress.js.txt     multiplierHolder_stress.js      
mv owned.js.txt     owned.js      
mv regulator_tollBoothOperator_student.js.txt     regulator_tollBoothOperator_student.js      
mv scenarios.js.txt     scenarios.js      
mv testDepositHolder.js.txt     testDepositHolder.js      
mv testMultiplierHolder.js.txt     testMultiplierHolder.js      
mv TestOwnedA.sol.txt     TestOwnedA.sol      
mv TestOwnedB.sol.txt     TestOwnedB.sol      
mv TestOwnedC.sol.txt     TestOwnedC.sol      
mv TestLinkedListQueue.sol.txt     TestLinkedListQueue.sol      
mv testRegulated.js.txt     testRegulated.js      
mv testRegulator.js.txt     testRegulator.js      
mv testRoutePriceHolder.js.txt     testRoutePriceHolder.js      
mv TestRoutePriceHolderA.sol.txt     TestRoutePriceHolderA.sol      
mv TestRoutePriceHolderB.sol.txt     TestRoutePriceHolderB.sol      
mv testTollBoothHolder.js.txt     testTollBoothHolder.js      
mv testTollBoothOperator.js.txt     testTollBoothOperator.js      
mv tollBoothOperator_student.js.txt     tollBoothOperator_student.js      
mv tollBoothOperator.js.txt tollBoothOperator.js