mv multiplierHolder.js   multiplierHolder.js.txt
mv multiplierHolder_stress.js   multiplierHolder_stress.js.txt
mv owned.js   owned.js.txt
mv regulator_tollBoothOperator_student.js   regulator_tollBoothOperator_student.js.txt
mv scenarios.js   scenarios.js.txt
mv testDepositHolder.js   testDepositHolder.js.txt
mv testMultiplierHolder.js   testMultiplierHolder.js.txt
mv TestOwnedA.sol   TestOwnedA.sol.txt
mv TestOwnedB.sol   TestOwnedB.sol.txt
mv TestOwnedC.sol   TestOwnedC.sol.txt
mv TestLinkedListQueue.sol     TestLinkedListQueue.sol.txt
mv testRegulated.js   testRegulated.js.txt
mv testRegulator.js   testRegulator.js.txt
mv testRoutePriceHolder.js   testRoutePriceHolder.js.txt
mv TestRoutePriceHolderA.sol   TestRoutePriceHolderA.sol.txt
mv TestRoutePriceHolderB.sol   TestRoutePriceHolderB.sol.txt
mv testTollBoothHolder.js   testTollBoothHolder.js.txt
mv testTollBoothOperator.js   testTollBoothOperator.js.txt
mv tollBoothOperator_student.js   tollBoothOperator_student.js.txt
mv tollBoothOperator.js tollBoothOperator.js.txt